language: node_js
node_js: "8"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
services:
  - mongodb
before_script:
  - sleep 10
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
